#!/usr/bin/env python

import sys

from embedvm import asm

def main():
    a = asm.ASM()
    data = open(sys.argv[1]).read()
    a.read_asm(data)
    print sorted(a.jumplabels.keys())
    converted = "".join(map(chr, a.write_binary()))
    with open(sys.argv[2], 'w') as f:
        f.write(converted)

if __name__ == "__main__":
    main()
