#!/usr/bin/env python

import sys

from embedvm import asm

def main():
    a = asm.ASM()
    data = open(sys.argv[1]).read()
    a.read_asm(data)
    a.fix_all()
    converted = "".join(map(chr, a.to_binary()))
    with open(sys.argv[2], 'w') as f:
        f.write(converted)

if __name__ == "__main__":
    main()
