#!/usr/bin/env python

import sys
from embedvm.asm import ASM
from embedvm import python_writer # monkey patching

def main():
    a = ASM()
    a.read_binary([ord(x) for x in open(sys.argv[1]).read()], int(sys.argv[2]))
    converted = a.get_python()
    with open(sys.argv[3], 'w') as f:
        f.write(converted)

if __name__ == "__main__":
    main()
