#!/usr/bin/env python

import sys

from embedvm import asm

def main():
    a = asm.ASM()
    data = map(ord, open(sys.argv[1]).read())
    a.read_binary(data, int(sys.argv[2]))
    converted = a.write_asm()
    with open(sys.argv[3], 'w') as f:
        f.write(converted)

if __name__ == "__main__":
    main()
